global:
  imageRegistry: "ghcr.io/sreekanthca6"
  imagePullPolicy: Always   # always pull dev-latest, never use a stale cached layer
  otelEndpoint: http://otel-collector-opentelemetry-collector.observability:4317

frontend:
  image:
    tag: dev-latest
  replicaCount: 1
  env:
    BACKEND_URL: http://kalemart-backend:4000
    HOSTNAME: "0.0.0.0"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

backend:
  image:
    tag: dev-latest
  replicaCount: 1
  env:
    NODE_ENV: development
    GRAFANA_URL: "http://localhost:3001"
    PROMETHEUS_URL: "http://localhost:9090"
    ALERTMANAGER_URL: "http://localhost:9093"
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

worker:
  image:
    tag: dev-latest
  replicaCount: 1
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

aiService:
  image:
    tag: dev-latest
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

sreAgent:
  image:
    tag: dev-latest

ingress:
  enabled: true
  className: nginx
  host: kalemart.local
  tls:
    enabled: false
