{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kalemart-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kalemart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "kalemart.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
{{- end }}
