{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kalemart-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kalemart.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kalemart.name" . }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kalemart.name" . }}
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ include "kalemart.image" (dict "global" .Values.global "image" .Values.backend.image) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            {{- range $k, $v := .Values.backend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- include "kalemart.otelEnv" (dict "Values" .Values "component" "backend") | nindent 12 }}
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: kalemart-secrets
                  key: ANTHROPIC_API_KEY
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: kalemart-secrets
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kalemart-secrets
                  key: JWT_SECRET
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
