apiVersion: v1
kind: Secret
metadata:
  name: kalemart-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kalemart.labels" . | nindent 4 }}
type: Opaque
data:
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
