apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: "*"
    helm:
      parameters:
        - name: tempo.storage.trace.backend
          value: local
        - name: tempo.storage.trace.local.path
          value: /var/tempo/traces
        - name: persistence.enabled
          value: "false"
        - name: resources.requests.memory
          value: 128Mi
        - name: resources.limits.memory
          value: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
