# Auto-generated by Terraform — do not edit by hand.
# Regenerate with: terraform apply (triggers local_file resource)

[k3s_server]
${server_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[k3s_agent]
${agent_ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=~/.ssh/google_compute_engine

[k3s_cluster:children]
k3s_server
k3s_agent

[k3s_cluster:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
