---
k3s_version: "v1.31.4+k3s1"

# Internal IP of the server node — agents use this to join
# Populated at runtime from hostvars
k3s_server_internal_ip: "{{ hostvars[groups['k3s_server'][0]]['ansible_default_ipv4']['address'] }}"
